// ------------------------------------------------------------------------------------------------
// <copyright file="HyphaKnowledgeOptionsTests.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Hypha.Knowledge.Tests
{
    using System;
    using System.IO;
    using System.Linq;
    using System.Net.Http;

    using Hypha.Knowledge;
    using Hypha.Knowledge.Generation;
    using Hypha.Knowledge.Layout;
    using Hypha.Knowledge.Releases;

    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Logging;

    /// <summary>
    /// Tests for the one place a caller can vary how fetching and generation behave.
    /// </summary>
    [TestFixture]
    public class HyphaKnowledgeOptionsTests
    {
        [Test]
        public void Every_setting_has_a_working_default()
        {
            // A caller inside the repository should be able to say AddHyphaKnowledge() and nothing else.
            var options = new HyphaKnowledgeOptions();

            Assert.Multiple(() =>
            {
                Assert.That(options.ApiBaseAddress, Is.EqualTo(Upstream.DefaultApiBaseAddress));
                Assert.That(options.RawContentBaseAddress, Is.EqualTo(Upstream.DefaultRawContentBaseAddress));
                Assert.That(options.MaxDownloadConcurrency, Is.EqualTo(6));
                Assert.That(options.Token, Is.Null);
                Assert.That(options.RepositoryRoot, Is.Null);
                Assert.That(() => options.Validate(), Throws.Nothing);
            });
        }

        [Test]
        public void A_concurrency_below_one_is_refused_at_registration()
        {
            // Caught while composing rather than on the first download, where the stack would be
            // several layers away from the setting that caused it.
            Assert.Throws<ArgumentOutOfRangeException>(
                () => new ServiceCollection().AddHyphaKnowledge(o => o.MaxDownloadConcurrency = 0));
        }

        [Test]
        public void The_options_are_resolvable_so_a_caller_can_read_what_it_composed()
        {
            using var provider = new ServiceCollection()
                .AddHyphaKnowledge(o => o.MaxDownloadConcurrency = 3)
                .BuildServiceProvider();

            Assert.That(
                provider.GetRequiredService<HyphaKnowledgeOptions>().MaxDownloadConcurrency, Is.EqualTo(3));
        }

        [Test]
        public void The_api_host_reaches_the_client_and_the_layout_reaches_the_root()
        {
            var host = new Uri("https://ghe.example.invalid/api/v3/");
            var root = new DirectoryInfo(TestContext.CurrentContext.WorkDirectory);

            using var provider = new ServiceCollection()
                .AddHyphaKnowledge(o =>
                {
                    o.ApiBaseAddress = host;
                    o.RepositoryRoot = root;
                })
                .BuildServiceProvider();

            Assert.Multiple(() =>
            {
                Assert.That(
                    provider.GetRequiredService<IHttpClientFactory>()
                        .CreateClient(ServiceCollectionExtensions.UpstreamClientName).BaseAddress,
                    Is.EqualTo(host));
                Assert.That(
                    provider.GetRequiredService<IKnowledgeLayout>().Root.FullName, Is.EqualTo(root.FullName));
            });
        }

        [Test]
        public void The_raw_content_host_reaches_the_grammar_reference()
        {
            // The one setting that shows up in generated bytes rather than in a request.
            using var provider = new ServiceCollection()
                .AddHyphaKnowledge(o => o.RawContentBaseAddress = new Uri("https://mirror.invalid/"))
                .BuildServiceProvider();

            var rendered = provider.GetRequiredService<Grammar.IGrammarReference>().RenderGraphical(
                "2026-05",
                "owner/repo",
                new Grammar.GrammarParser().ParseGraphical(GraphicalGrammarParserTests.Graphical));

            Assert.That(rendered, Does.Contain("https://mirror.invalid/owner/repo/2026-05/bnf/"));
        }

        [Test]
        public void Logging_is_available_to_every_generator()
        {
            // #77 needs somewhere for install-time progress to go; without AddLogging the generators
            // would not even resolve.
            using var provider = new ServiceCollection().AddHyphaKnowledge().BuildServiceProvider();

            Assert.Multiple(() =>
            {
                Assert.That(provider.GetService<ILoggerFactory>(), Is.Not.Null);
                Assert.That(provider.GetServices<IKnowledgeGenerator>().ToList(), Has.Count.EqualTo(3));
            });
        }
    }
}
