// ------------------------------------------------------------------------------------------------
// <copyright file="GrammarReference.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Hypha.Knowledge.Grammar
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;

    using Hypha.Knowledge.Releases;

    /// <summary>
    /// Renders the per-release grammar references under <c>knowledge/&lt;tag&gt;/textual-notation/</c>.
    /// </summary>
    public sealed class GrammarReference : IGrammarReference
    {
        private readonly string rawContentBase;

        /// <summary>
        /// Initializes a new instance of the <see cref="GrammarReference"/> class.
        /// </summary>
        /// <param name="rawContentBaseAddress">
        /// Where a file at a tag is served from; defaults to <see cref="Upstream.DefaultRawContentBaseAddress"/>.
        /// Injectable for the same reason as the API host - an enterprise instance serves its raw
        /// content from somewhere else.
        /// </param>
        public GrammarReference(Uri? rawContentBaseAddress = null) =>
            this.rawContentBase = (rawContentBaseAddress ?? Upstream.DefaultRawContentBaseAddress).ToString();

        /// <inheritdoc/>
        /// <param name="grammar">The grammar's name, <c>KerML</c> or <c>SysML</c>.</param>
        /// <param name="tag">The release the grammar was read at.</param>
        /// <param name="productions">The parsed productions, in document order.</param>
        public string Render(string grammar, string tag, IReadOnlyList<Production> productions)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(grammar);
            ArgumentException.ThrowIfNullOrWhiteSpace(tag);
            ArgumentNullException.ThrowIfNull(productions);

            var lines = new List<string>
            {
                "---",
                $"grammar: {grammar}",
                $"tag: {tag}",
                "kind: grammar-reference",
                $"productions: {productions.Count.ToString(CultureInfo.InvariantCulture)}",
                "---",
                string.Empty,
                $"# {grammar} textual grammar — {tag}",
                string.Empty,
                "> Generated by `tools/knowledge-gen` from the committed `.kebnf` (EPL-2.0) — do not edit by",
                "> hand; re-run the generator.",
                string.Empty,
                "Each production shows the metaclass it builds (`produces`), the specification clause it is",
                "defined in, and the metamodel features it populates (`=` sets, `+=` adds, `?=` is a boolean",
                "flag). Both come from the grammar itself, not from name matching.",
                string.Empty,
            };

            (string? Clause, string Title)? current = null;

            foreach (var production in productions)
            {
                var key = (production.Clause, production.ClauseTitle);
                if (current != key)
                {
                    current = key;
                    lines.Add($"## {Heading(production, "Lexical")}");
                    lines.Add(string.Empty);
                }

                lines.Add($"### {production.Name}");
                lines.Add(string.Empty);

                var facts = new List<string>();

                if (!string.IsNullOrEmpty(production.Produces))
                {
                    facts.Add(
                        $"produces [{production.Produces}](../metamodel/elements/{production.Produces}.md)");
                }

                if (!string.IsNullOrEmpty(production.Clause))
                {
                    facts.Add($"clause `{production.Clause}`");
                }

                if (production.Features.Count > 0)
                {
                    facts.Add("features " + string.Join(
                        ", ",
                        production.Features.Select(feature => $"`{feature.Feature} {feature.Operator}`")));
                }

                if (facts.Count > 0)
                {
                    lines.Add(string.Join(" · ", facts));
                    lines.Add(string.Empty);
                }

                lines.Add("```kebnf");
                lines.Add(production.Body);
                lines.Add("```");
                lines.Add(string.Empty);
            }

            return string.Join("\n", lines);
        }

        /// <inheritdoc/>
        /// <remarks>
        /// The notation itself is a set of SVGs published alongside the grammar. They are linked at the
        /// release tag rather than copied in: 284 images per release is 1.5 MB of binaries nothing in
        /// the knowledge base would read, and the link is stable because the tag is.
        /// </remarks>
        /// <param name="tag">The release the grammar was read at, which the image links point into.</param>
        /// <param name="repository">The upstream the images are published from.</param>
        /// <param name="productions">The parsed graphical productions, in document order.</param>
        public string RenderGraphical(string tag, string repository, IReadOnlyList<Production> productions)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(tag);
            ArgumentException.ThrowIfNullOrWhiteSpace(repository);
            ArgumentNullException.ThrowIfNull(productions);

            var withImages = productions.Count(production => production.Images.Count > 0);

            var lines = new List<string>
            {
                "---",
                "grammar: SysML-graphical",
                $"tag: {tag}",
                "kind: graphical-grammar-reference",
                $"productions: {productions.Count.ToString(CultureInfo.InvariantCulture)}",
                $"withImages: {withImages.ToString(CultureInfo.InvariantCulture)}",
                "---",
                string.Empty,
                $"# SysML graphical notation — {tag}",
                string.Empty,
                "> Generated by `tools/knowledge-gen` from the committed `.kgbnf` (EPL-2.0) — do not edit by",
                "> hand; re-run the generator.",
                string.Empty,
                "Most graphical productions *are* a picture. The images are linked at this release's tag",
                "rather than copied into the repository, so they stay in step with the grammar.",
                string.Empty,
            };

            (string? Clause, string Title)? current = null;

            foreach (var production in productions)
            {
                var key = (production.Clause, production.ClauseTitle);
                if (current != key)
                {
                    current = key;
                    lines.Add($"## {Heading(production, "General")}");
                    lines.Add(string.Empty);
                }

                lines.Add($"### {production.Name}");
                lines.Add(string.Empty);

                if (!string.IsNullOrEmpty(production.Clause))
                {
                    lines.Add($"clause `{production.Clause}`");
                    lines.Add(string.Empty);
                }

                foreach (var path in production.Images)
                {
                    lines.Add($"![{production.Name}]({this.rawContentBase}{repository}/{tag}/bnf/{path})");
                    lines.Add(string.Empty);
                }

                lines.Add("```kgbnf");
                lines.Add(production.Body);
                lines.Add("```");
                lines.Add(string.Empty);
            }

            return string.Join("\n", lines);
        }

        /// <summary>
        /// The section heading for a production's clause, or <paramref name="unattributed"/> for the
        /// productions the grammar states no clause for.
        /// </summary>
        private static string Heading(Production production, string unattributed) =>
            string.IsNullOrEmpty(production.Clause)
                ? unattributed
                : $"{production.Clause} {production.ClauseTitle}".Trim();
    }
}
